---
version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/opt/app/src
    container_name: ts-node-docker
    env_file: .env
    expose:
      - "4000"
    ports:
      - ${PORT}:${PORT}
    networks:
      - api
    depends_on:
      - postgres
    command: npm run dev
    
  postgres:
    image: postgres:15.1
    container_name: ehm-postgres
    env_file: .env
    networks:
      - api
    ports:
      - 5432:5432
    volumes:
      - ehm-pg-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  api:
  
volumes:
  ehm-pg-data:
      