# https://taskfile.dev

version: '3'

tasks:
  run-dev: 
    cmds:
      - docker compose up -d 

  run-prod: 
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

  down: 
    cmds:
      - docker compose down

