# https://taskfile.dev

version: '3'

tasks:
  dev_debug: 
    cmds:
      - npx nodemon --inspect -r dotenv/config ./app.js
    silent: true

  dev_start:
    cmds:
      - npx nodemon -r dotenv/config ./app.js
    silent: true
  
  prod_start:
    cmds:
      - node -r dotenv/config app.js
    silent: true
