# https://taskfile.dev

version: '3'

tasks:
  dev_debug: 
    cmds:
      - npx nodemon -r dotenv/config ./src/app.ts
    silent: true

  prod_start:
    cmds:
      - npx tsc
      - node -r dotenv/config ./build/app.js
    silent: true
