name: CI for devops final task
on:
  push: {}
  release:
    types: [published]
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag: 
        default: latest
        description: image tag

env:
  IMAGE_TITLE: ehm-course-project
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Project
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: ./Dockerfile
          push: false
          tags: ${{ env.IMAGE_TITLE }}:${{ env.TAG }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

